"""add material_types table and type_id to materials

Revision ID: 5ae59e2b2636
Revises: 511b42f31ef2
Create Date: 2026-09-28 11:18:46.825721

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ae59e2b2636"
down_revision: str | Sequence[str] | None = "511b42f31ef2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_types",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("changed_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_materials_type_id", "material_types", ["type_id"], ["id"], ondelete="SET NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.drop_constraint("fk_materials_type_id", type_="foreignkey")
        batch_op.drop_column("type_id")

    op.drop_table("material_types")
    # ### end Alembic commands ###
