"""Initial tables

Revision ID: 6b915867262d
Revises: 
Create Date: 2026-08-11 22:29:33.974083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b915867262d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('positions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('directors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('server_address_slug', sa.String(length=200), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn'),
    sa.UniqueConstraint('name')
    )
    op.create_table('counterparties',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('requests',
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ZAPROS', 'TENDER', 'NOT_ACTUAL', 'DOC_PROCESSING', 'DOC_SIGNING', 'WAITING_PAYMENT', 'ORDER', name='requeststatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tkp_num', sa.String(length=50), nullable=True),
    sa.Column('bktpb', sa.Integer(), nullable=False),
    sa.Column('ktpb', sa.Integer(), nullable=False),
    sa.Column('ktp', sa.Integer(), nullable=False),
    sa.Column('kso_393', sa.Integer(), nullable=False),
    sa.Column('kso_204', sa.Integer(), nullable=False),
    sa.Column('k_104', sa.Integer(), nullable=False),
    sa.Column('k_104m', sa.Integer(), nullable=False),
    sa.Column('sho', sa.Integer(), nullable=False),
    sa.Column('pku', sa.Integer(), nullable=False),
    sa.Column('pus', sa.Integer(), nullable=False),
    sa.Column('parn', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('counterparties')
    op.drop_table('organizations')
    op.drop_table('directors')
    op.drop_table('positions')
    op.drop_table('users')
    op.drop_table('managers')
    # ### end Alembic commands ###
